// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlGzhW9UWlzv4F_QxZZEfo_mxM6zozEUs',
    appId: '1:559786376992:web:d05b147a4e1f928341e145',
    messagingSenderId: '559786376992',
    projectId: 'travelling-with-flutter',
    authDomain: 'travelling-with-flutter.firebaseapp.com',
    storageBucket: 'travelling-with-flutter.firebasestorage.app',
    measurementId: 'G-VNZ68XB6WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4iRrLj9_V8_gtNfPMBwAKdGSlB22kAIY',
    appId: '1:559786376992:android:f5d8a5c8c9e06c2741e145',
    messagingSenderId: '559786376992',
    projectId: 'travelling-with-flutter',
    storageBucket: 'travelling-with-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqXZvpf4cTzz3ZTPvMtQPV19POPQpKYXU',
    appId: '1:559786376992:ios:0e69a98d67455a2041e145',
    messagingSenderId: '559786376992',
    projectId: 'travelling-with-flutter',
    storageBucket: 'travelling-with-flutter.firebasestorage.app',
    iosBundleId: 'com.example.lab05Example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqXZvpf4cTzz3ZTPvMtQPV19POPQpKYXU',
    appId: '1:559786376992:ios:0e69a98d67455a2041e145',
    messagingSenderId: '559786376992',
    projectId: 'travelling-with-flutter',
    storageBucket: 'travelling-with-flutter.firebasestorage.app',
    iosBundleId: 'com.example.lab05Example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlGzhW9UWlzv4F_QxZZEfo_mxM6zozEUs',
    appId: '1:559786376992:web:6467f1c3547100df41e145',
    messagingSenderId: '559786376992',
    projectId: 'travelling-with-flutter',
    authDomain: 'travelling-with-flutter.firebaseapp.com',
    storageBucket: 'travelling-with-flutter.firebasestorage.app',
    measurementId: 'G-L4PFCNMCRR',
  );
}
