import 'package:flutter/widgets.dart';

String appText(BuildContext context, String source) {
  final locale = Localizations.maybeLocaleOf(context);
  if (locale?.languageCode != 'zh') return source;
  if (source.startsWith('of ')) return '總預算 ${source.substring(3)}';
  if (source.contains(' route / ')) {
    return source
        .replaceFirst(' route / ', ' 路線 / ')
        .replaceFirst(' stops', ' 站');
  }
  return _zhHantTwText[source] ?? source;
}

const _zhHantTwText = {
  'Home': '首頁',
  'Trips': '旅程',
  'Chat': '聊天',
  'Profile': '個人資料',
  'Info': '資訊',
  'Map': '地圖',
  'Translate': '翻譯',
  'AI': 'AI',
  'Ready for your next Adventure': '準備好下一段冒險',
  'AI Travel Agent': 'AI 旅行助理',
  'UP NEXT': '下一站',
  'Kyoto City Zoo': '京都市動物園',
  'Overview': '總覽',
  'Itinerary': '行程',
  'Checklist': '清單',
  'Day': '第',
  'Add to': '新增到',
  'New activity': '新活動',
  'New booking': '新預訂',
  'New trip': '新旅程',
  'None': '無',
  'Travelling with Flutter': 'Travelling with Flutter',
  'Tokyo, Japan': '東京，日本',
  'Sign in to keep your trips, AI plans, budgets, and packing lists synced.':
      '登入即可同步你的旅程、AI 計畫、預算和打包清單。',
  'or': '或',
  'I already have an account': '我已經有帳號',
  'Create a new account': '建立新帳號',
  'Pick your travel style': '選擇你的旅行風格',
  'Choose the things you usually look for so routes, packing lists, and budgets start closer to your taste.':
      '選擇你平常重視的旅行元素，路線、打包清單和預算會更貼近你的偏好。',
  'Shopping': '購物',
  'Museums': '博物館',
  'Hidden Gems': '私房景點',
  'Culture': '文化',
  'Zen': '禪意',
  'City': '城市',
  'Romantic': '浪漫',
  'Scenic': '景觀',
  'Sunset': '夕陽',
  'Relax': '放鬆',
  'Nightlife': '夜生活',
  'Adventure': '冒險',
  'Budget-friendly': '平價',
  'Luxury': '奢華',
  'Walking': '步行',
  'Beach': '海灘',
  'Gate changed': '登機門變更',
  'Flight JAL 402 now boards at Gate A7.': 'JAL 402 航班現在改在 A7 登機門登機。',
  'Rain window': '降雨時段',
  'Kyoto rain expected after 2 PM.': '京都下午 2 點後可能下雨。',
  'ADD PRIMARY PHOTO': '新增主要照片',
  'Tell AI the basics below. It will build stops, bookings, and a packing list.':
      '告訴 AI 基本資訊，它會建立停靠點、預訂和打包清單。',
  'AI generation was unavailable, so a local draft plan was created.':
      'AI 生成功能暫時無法使用，因此已建立本機草稿計畫。',
  'Generating itinerary...': '正在產生行程...',
  'AI is shaping the route, bookings, budget, and packing list.':
      'AI 正在整理路線、預訂、預算和打包清單。',
  'Ask for routes, food, bookings, packing, or swaps.': '詢問路線、美食、預訂、打包或替換方案。',
  'Vote on lunch and share plan changes with friends.': '和朋友投票決定午餐，並分享計畫變更。',
  'AI Agent active. I can optimize routes, compare ideas, and turn chat into itinerary changes.':
      'AI 助理已啟用。我可以最佳化路線、比較想法，並把聊天內容轉成行程變更。',
  'I could not generate a travel suggestion right now.': '我現在無法產生旅行建議。',
  'AI chat is unavailable right now. Please try again in a moment.':
      'AI 聊天目前無法使用，請稍後再試。',
  'Ask for route changes, cheaper options, packing help, or booking reminders.':
      '詢問路線變更、更便宜的選項、打包協助或預訂提醒。',
  'Keep this window open while the SMS arrives.': '等待簡訊時請保持此視窗開啟。',
  'Phone SMS sign-in works on web, Android, and iOS. Use email on this device.':
      '電話簡訊登入支援 Web、Android 和 iOS。此裝置請使用電子郵件登入。',
  'Enter your email first.': '請先輸入電子郵件。',
  'Password reset email sent.': '密碼重設郵件已送出。',
  'Use international phone format, for example +15551234567.':
      '請使用國際電話格式，例如 +15551234567。',
  'SMS code sent.': '簡訊驗證碼已送出。',
  'Send an SMS code first.': '請先傳送簡訊驗證碼。',
  'Could not sign in.': '無法登入。',
  'Enter a valid email.': '請輸入有效的電子郵件。',
  'Use at least 6 characters.': '請至少使用 6 個字元。',
  'Use international format with + country code.': '請使用含 + 國碼的國際格式。',
  'Enter the 6-digit SMS code.': '請輸入 6 位數簡訊驗證碼。',
  'That email already has an account.': '該電子郵件已經有帳號。',
  'Enter a valid email address.': '請輸入有效的電子郵件地址。',
  'Email or password is incorrect.': '電子郵件或密碼不正確。',
  'No account was found for that email.': '找不到該電子郵件的帳號。',
  'Use a stronger password.': '請使用更強的密碼。',
  'Check your connection and try again.': '請檢查網路連線後再試一次。',
  'Too many attempts. Try again later.': '嘗試次數過多，請稍後再試。',
  'This sign-in provider is not enabled in Firebase.': 'Firebase 尚未啟用此登入提供者。',
  'The sign-in window was closed.': '登入視窗已關閉。',
  'The SMS code is not correct.': '簡訊驗證碼不正確。',
  'Enter a valid phone number with country code.': '請輸入含國碼的有效電話號碼。',
  'Could not sign in. Please try again.': '無法登入，請再試一次。',
  'Please sign out, sign in again, then delete the account.':
      '請先登出、重新登入，然後再刪除帳號。',
  'Kyoto Group': '京都群組',
  'Ask about Kyoto, budgets, packing...': '詢問京都、預算、打包清單...',
  'Important updates': '重要更新',
  'AI planning cards': 'AI 規劃卡片',
  'Food': '美食',
  'Route': '路線',
  'Market lunch': '市場午餐',
  'Less walking': '減少步行',
  'Travel interests': '旅行興趣',
  'Start exploring': '開始探索',
  'Performance': '效能',
  'Preset': '預設模式',
  'Custom': '自訂',
  'Current behavior': '目前行為',
  'Power': '耗電',
  'Estimated impact': '估計影響',
  'Motion': '動態效果',
  'High': '高效能',
  'Balanced': '平衡',
  'Battery saver': '省電',
  'Full motion': '完整動態',
  'Reduced motion': '減少動態',
  'Off': '關閉',
  'Native': '原生',
  'Conservative': '保守',
  'Low': '低',
  'Moderate': '中等',
  'Higher': '較高',
  'Use normal Flutter frame pacing.': '使用 Flutter 一般畫面節奏。',
  'Keep transitions short and decorative loops off unless enabled.':
      '縮短轉場，除非啟用否則關閉裝飾循環動畫。',
  'Prefer static visuals and minimal animation work.': '偏好靜態畫面並減少動畫工作。',
  'Advanced': '進階',
  'Animations': '動畫',
  'Frame pacing': '畫面節奏',
  'Image quality': '圖片品質',
  'Cache pages': '快取頁面',
  'Keep tab pages alive instead of rebuilding from zero.': '保留分頁狀態，避免從零重建。',
  'Repaint isolation': '重繪隔離',
  'Wrap major pages in repaint boundaries.': '用重繪邊界包住主要頁面。',
  'Heavy visual effects': '高負載視覺效果',
  'Allow decorative animated visuals when enabled.': '啟用時允許裝飾性動畫視覺效果。',
  'Booking': '訂位',
  'Budget': '預算',
  'Dates': '日期',
  'Party': '旅伴',
  'ongoing': '進行中',
  'upcoming': '即將開始',
  'completed': '已完成',
  'TBD': '待定',
  'Confirmed': '已確認',
  'Review': '檢查',
  'AI Prepared': 'AI 已準備',
  'Cheaper': '更便宜',
  'More food': '更多美食',
  'Slower': '慢一點',
  'Nature': '自然',
  'Customize': '自訂',
  'CUSTOMIZE': '自訂',
  'CONFIRM': '確認',
  'CONFIRMED': '已確認',
  'USE CUSTOMIZED PLAN': '使用自訂計畫',
  'Thinking...': '思考中...',
  'Start date': '開始日期',
  'End date': '結束日期',
  'Trip dates': '旅程日期',
  'Trip tags': '旅程標籤',
  'Bookings': '預訂',
  'First stops': '前幾站',
  'Add stop': '新增停靠點',
  'Activity': '活動',
  'Time': '時間',
  'Cost': '費用',
  'Cancel': '取消',
  'Add': '新增',
  'Route map': '路線地圖',
  'Open map': '開啟地圖',
  'Checklist item': '清單項目',
  'Add booking': '新增預訂',
  'Title': '標題',
  'Date': '日期',
  'Reference': '參考編號',
  'Open chat': '開啟聊天',
  'Planned': '預計',
  'Actual': '實際',
  'Free': '免費',
  'Start': '開始',
  'Travel Info': '旅行資訊',
  'Weather': '天氣',
  'Rain expected after 2 PM. Move outdoor shrines earlier.':
      '下午 2 點後可能下雨。建議把戶外神社行程提前。',
  'Transport': '交通',
  'IC cards work across trains and buses around central Kyoto.':
      'IC 卡可用於京都市中心多數電車與公車。',
  'Local costs': '當地花費',
  'Temples are often low-cost; cash is still useful for markets.':
      '寺廟通常花費不高；市場仍建議準備現金。',
  'Where is Kyoto Station?': '京都車站在哪裡？',
  'No pork, please.': '請不要豬肉。',
  'I have a reservation.': '我有預約。',
  'Spent': '已花費',
  'Stay': '住宿',
  'Activities': '活動',
  'Essentials': '必需品',
  'Passport': '護照',
  'Travel adapter': '旅行轉接頭',
  'Power bank': '行動電源',
  'Clothing': '衣物',
  'Comfortable walking shoes': '舒適步行鞋',
  'Light rain jacket': '輕便雨衣',
  'Arrive at Kyoto Station': '抵達京都車站',
  'Nishiki Market Food Tour': '錦市場美食導覽',
  'Fushimi Inari-taisha Hike': '伏見稻荷大社健行',
  'Kinkaku-ji Golden Pavilion': '金閣寺',
  'Gion District Walk': '祇園散步',
  'AI Packing List': 'AI 打包清單',
  'How do you want to start?': '你想怎麼開始？',
  'Plan Step-by-Step': '逐步規劃',
  'Explore ideas, compare pacing, then let AI draft it.':
      '探索想法、比較節奏，再讓 AI 草擬行程。',
  'Plan with AI': '用 AI 規劃',
  'Search a real city, choose dates, tags, and generate.': '搜尋真實城市、選擇日期與標籤後產生。',
  'Create Manually': '手動建立',
  'Enter destination, dates, budget, people, and tags.': '輸入目的地、日期、預算、旅伴與標籤。',
  'Use Saved Trip Template': '使用已儲存旅程範本',
  'Start from a polished Kyoto sample and edit later.': '從整理好的京都範例開始，之後再編輯。',
  'Hello, where would you like to go?': '你好，想去哪裡？',
  'Choose guided suggestions or describe the full trip.': '選擇引導建議，或直接描述完整旅程。',
  'Describe the trip...': '描述這趟旅程...',
  'Type changes or confirm...': '輸入修改或確認...',
  'AI Flow': 'AI 流程',
  'Manual': '手動',
  'Generate with AI': '使用 AI 產生',
  'Create itinerary': '建立行程',
  'Destination': '目的地',
  'Search a real city': '搜尋真實城市',
  'Currency': '貨幣',
  'Total budget': '總預算',
  'US dollars': '美元',
  'New Taiwan dollars': '新台幣',
  'Indonesian rupiah': '印尼盾',
  'Japanese yen': '日圓',
  'euros': '歐元',
  'Who is coming': '同行者',
  'Airline optional': '航空公司（選填）',
  'Confirmation': '確認碼',
  'Add custom tag': '新增自訂標籤',
  'Save draft edits': '儲存草稿修改',
  'Popular starting points': '熱門起點',
  'Trip length': '旅程長度',
  'Travel party': '同行者',
  'Solo': '獨旅',
  'Friends': '朋友',
  'Family': '家人',
  'Tour': '旅行團',
  'Comfortable timing': '舒適的時間安排',
  'Shared plans and votes': '共享計畫與投票',
  'Personal route and pace': '個人路線與節奏',
  'Balanced pace': '平衡節奏',
  'Fast weekend plan': '快速週末計畫',
  'More room for day trips': '更多一日遊空間',
  'Lean and efficient': '精簡有效率',
  'Comfortable mid-range': '舒適中等預算',
  'More flexible picks': '更彈性的選擇',
  'Name': '姓名',
  'Language': '語言',
  'Notifications': '通知',
  'Theme': '主題',
  'Light': '淺色',
  'Dark': '深色',
  'Save profile': '儲存個人資料',
  'Sign out': '登出',
  'Delete account': '刪除帳戶',
  'Email': '電子郵件',
  'Phone': '電話',
  'Continue with Google': '使用 Google 繼續',
  'Facebook setup needed': '需要設定 Facebook',
  'Password': '密碼',
  'Create account': '建立帳戶',
  'Sign in': '登入',
  'Forgot password?': '忘記密碼？',
  'Phone number': '電話號碼',
  'SMS code': '簡訊驗證碼',
  'Verify code': '驗證代碼',
  'Send SMS code': '傳送簡訊代碼',
  'Resend code': '重新傳送代碼',
  'Change phone': '更改電話',
  'Login': '登入',
  'Customize AI Draft': '自訂 AI 草稿',
  'End': '結束',
  'English (US)': '英文（美國）',
  'Chinese (Taiwan / Traditional)': '繁體中文（台灣）',
  'e.g. anime, halal food, wheelchair access': '例如：動漫、清真食物、無障礙通行',
  'Remember me for 30 days': '記住我 30 天',
  'Useful while debugging. Sign out anytime from Profile.':
      '除錯時很方便。可隨時在個人資料登出。',
};
